services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./storage:/var/www/html/storage
    environment:
      - APP_ENV=production
    restart: unless-stopped

  worker:
    build: .
    command: php worker queue:work --timeout=3600
    volumes:
      - ./storage:/var/www/html/storage
    environment:
      - APP_ENV=production
    restart: unless-stopped
    depends_on:
      - app
    deploy:
      replicas: 5

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=http://localhost:8080
    ports:
      - "3000:80"
    depends_on:
      - app
    restart: unless-stopped
